// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaklaciGuvercin.Infrastructure.Data;

#nullable disable

namespace TaklaciGuvercin.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260101202229_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaklaciGuvercin.Domain.Entities.Bird", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FatherId")
                        .HasColumnType("uuid");

                    b.Property<int>("Generation")
                        .HasColumnType("integer");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastFedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("integer");

                    b.Property<int>("MaxStamina")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MotherId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RestingUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SickUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Stamina")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("State");

                    b.ToTable("Birds");
                });

            modelBuilder.Entity("TaklaciGuvercin.Domain.Entities.Encounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CoinsLooted")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InitiatorPlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("InitiatorPower")
                        .HasColumnType("integer");

                    b.Property<Guid>("InitiatorSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("InitiatorWasOnline")
                        .HasColumnType("boolean");

                    b.Property<string>("LootedBirdIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RandomRoll")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TargetPlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetPower")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TargetWasOnline")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WinnerPlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InitiatorPlayerId");

                    b.HasIndex("State");

                    b.HasIndex("TargetPlayerId");

                    b.ToTable("Encounters");
                });

            modelBuilder.Entity("TaklaciGuvercin.Domain.Entities.FlightSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Altitude")
                        .HasColumnType("double precision");

                    b.Property<string>("BirdIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<int>("EncountersCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("FlightSessions");
                });

            modelBuilder.Entity("TaklaciGuvercin.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Coins")
                        .HasColumnType("integer");

                    b.Property<int>("CoopCapacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("PremiumCurrency")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBirdsLooted")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBirdsLost")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBirdsOwned")
                        .HasColumnType("integer");

                    b.Property<int>("TotalEncountersLost")
                        .HasColumnType("integer");

                    b.Property<int>("TotalEncountersWon")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TaklaciGuvercin.Domain.Entities.Bird", b =>
                {
                    b.OwnsOne("TaklaciGuvercin.Domain.ValueObjects.BirdDNA", "DNA", b1 =>
                        {
                            b1.Property<Guid>("BirdId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Element")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Element");

                            b1.Property<float>("MutationFactor")
                                .HasColumnType("real")
                                .HasColumnName("MutationFactor");

                            b1.HasKey("BirdId");

                            b1.ToTable("Birds");

                            b1.WithOwner()
                                .HasForeignKey("BirdId");

                            b1.OwnsOne("TaklaciGuvercin.Domain.ValueObjects.Gene", "CrestType", b2 =>
                                {
                                    b2.Property<Guid>("BirdDNABirdId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Allele1")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("CrestType_Allele1");

                                    b2.Property<string>("Allele2")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("CrestType_Allele2");

                                    b2.Property<string>("TraitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("CrestType_TraitName");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CrestType_Type");

                                    b2.HasKey("BirdDNABirdId");

                                    b2.ToTable("Birds");

                                    b2.WithOwner()
                                        .HasForeignKey("BirdDNABirdId");
                                });

                            b1.OwnsOne("TaklaciGuvercin.Domain.ValueObjects.Gene", "ElementGene", b2 =>
                                {
                                    b2.Property<Guid>("BirdDNABirdId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Allele1")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("ElementGene_Allele1");

                                    b2.Property<string>("Allele2")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("ElementGene_Allele2");

                                    b2.Property<string>("TraitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("ElementGene_TraitName");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("ElementGene_Type");

                                    b2.HasKey("BirdDNABirdId");

                                    b2.ToTable("Birds");

                                    b2.WithOwner()
                                        .HasForeignKey("BirdDNABirdId");
                                });

                            b1.OwnsOne("TaklaciGuvercin.Domain.ValueObjects.Gene", "HiddenTrait1", b2 =>
                                {
                                    b2.Property<Guid>("BirdDNABirdId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Allele1")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("HiddenTrait1_Allele1");

                                    b2.Property<string>("Allele2")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("HiddenTrait1_Allele2");

                                    b2.Property<string>("TraitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("HiddenTrait1_TraitName");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("HiddenTrait1_Type");

                                    b2.HasKey("BirdDNABirdId");

                                    b2.ToTable("Birds");

                                    b2.WithOwner()
                                        .HasForeignKey("BirdDNABirdId");
                                });

                            b1.OwnsOne("TaklaciGuvercin.Domain.ValueObjects.Gene", "HiddenTrait2", b2 =>
                                {
                                    b2.Property<Guid>("BirdDNABirdId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Allele1")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("HiddenTrait2_Allele1");

                                    b2.Property<string>("Allele2")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("HiddenTrait2_Allele2");

                                    b2.Property<string>("TraitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("HiddenTrait2_TraitName");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("HiddenTrait2_Type");

                                    b2.HasKey("BirdDNABirdId");

                                    b2.ToTable("Birds");

                                    b2.WithOwner()
                                        .HasForeignKey("BirdDNABirdId");
                                });

                            b1.OwnsOne("TaklaciGuvercin.Domain.ValueObjects.Gene", "Pattern", b2 =>
                                {
                                    b2.Property<Guid>("BirdDNABirdId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Allele1")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("Pattern_Allele1");

                                    b2.Property<string>("Allele2")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("Pattern_Allele2");

                                    b2.Property<string>("TraitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("Pattern_TraitName");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("Pattern_Type");

                                    b2.HasKey("BirdDNABirdId");

                                    b2.ToTable("Birds");

                                    b2.WithOwner()
                                        .HasForeignKey("BirdDNABirdId");
                                });

                            b1.OwnsOne("TaklaciGuvercin.Domain.ValueObjects.Gene", "PrimaryColor", b2 =>
                                {
                                    b2.Property<Guid>("BirdDNABirdId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Allele1")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("PrimaryColor_Allele1");

                                    b2.Property<string>("Allele2")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("PrimaryColor_Allele2");

                                    b2.Property<string>("TraitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("PrimaryColor_TraitName");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("PrimaryColor_Type");

                                    b2.HasKey("BirdDNABirdId");

                                    b2.ToTable("Birds");

                                    b2.WithOwner()
                                        .HasForeignKey("BirdDNABirdId");
                                });

                            b1.OwnsOne("TaklaciGuvercin.Domain.ValueObjects.Gene", "SecondaryColor", b2 =>
                                {
                                    b2.Property<Guid>("BirdDNABirdId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Allele1")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("SecondaryColor_Allele1");

                                    b2.Property<string>("Allele2")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("SecondaryColor_Allele2");

                                    b2.Property<string>("TraitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("SecondaryColor_TraitName");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("SecondaryColor_Type");

                                    b2.HasKey("BirdDNABirdId");

                                    b2.ToTable("Birds");

                                    b2.WithOwner()
                                        .HasForeignKey("BirdDNABirdId");
                                });

                            b1.OwnsOne("TaklaciGuvercin.Domain.ValueObjects.Gene", "TailType", b2 =>
                                {
                                    b2.Property<Guid>("BirdDNABirdId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Allele1")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("TailType_Allele1");

                                    b2.Property<string>("Allele2")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("TailType_Allele2");

                                    b2.Property<string>("TraitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("TailType_TraitName");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("TailType_Type");

                                    b2.HasKey("BirdDNABirdId");

                                    b2.ToTable("Birds");

                                    b2.WithOwner()
                                        .HasForeignKey("BirdDNABirdId");
                                });

                            b1.Navigation("CrestType")
                                .IsRequired();

                            b1.Navigation("ElementGene")
                                .IsRequired();

                            b1.Navigation("HiddenTrait1")
                                .IsRequired();

                            b1.Navigation("HiddenTrait2")
                                .IsRequired();

                            b1.Navigation("Pattern")
                                .IsRequired();

                            b1.Navigation("PrimaryColor")
                                .IsRequired();

                            b1.Navigation("SecondaryColor")
                                .IsRequired();

                            b1.Navigation("TailType")
                                .IsRequired();
                        });

                    b.OwnsOne("TaklaciGuvercin.Domain.ValueObjects.BirdStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("BirdId")
                                .HasColumnType("uuid");

                            b1.Property<int>("GeneticDominance")
                                .HasColumnType("integer")
                                .HasColumnName("GeneticDominance");

                            b1.Property<int>("Leadership")
                                .HasColumnType("integer")
                                .HasColumnName("Leadership");

                            b1.Property<int>("Loyalty")
                                .HasColumnType("integer")
                                .HasColumnName("Loyalty");

                            b1.Property<int>("Speed")
                                .HasColumnType("integer")
                                .HasColumnName("Speed");

                            b1.HasKey("BirdId");

                            b1.ToTable("Birds");

                            b1.WithOwner()
                                .HasForeignKey("BirdId");
                        });

                    b.Navigation("DNA")
                        .IsRequired();

                    b.Navigation("Stats")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
